### PR TITLE
Added notebook accompanying the upcoming blog post

### PR DESCRIPTION
**Pull request by aslisabanci**
Hi team, I need a place for my notebook to accompany my upcoming blog post. I also sent a PR to the `wip` of this repo. If that process is unnecessary, can you please just help me merge this to the main branch? Thanks!

Edit: This is the only blocker for our blog post to go, so I appreciate your quick review.

### CODE REVIEW

**Comment by mdhannadr** [comment]
@aslisabanci could you attach a requirements.txt file? Or further specify the necessary packages when pip installing in the first cell? I ran into a few installation problems because the packages I have installed are not backwards compatible:
```
tensorflow 2.5.0 requires numpy~=1.19.2, but you have numpy 1.24.1 which is incompatible.
datarobot-drum 1.5.15 requires datarobot==2.24.0, but you have datarobot 2.28.0 which is incompatible.
datarobot-drum 1.5.15 requires pyarrow==2.0.0, but you have pyarrow 6.0.1 which is incompatible.
```

**Comment by aslisabanci** [comment]
Thanks for the review @mdhannadr! Please check out my new commit. Btw, you don't need `datarobot-drum` for this notebook.

**Comment by mdhannadr** [comment]
Unfortunately I'm still getting an import error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnx 1.13.0 requires protobuf<4,>=3.20.2, but you have protobuf 3.19.6 which is incompatible.
```
Upgrading my version of `protobuf` sets off more errors:
```
tensorflow 2.9.2 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.12 which is incompatible.
tensorboard 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.12 which is incompatible.
onnx 1.13.0 requires protobuf<4,>=3.20.2, but you have protobuf 4.21.12 which is incompatible.
```

It seems that there is no version of protobuf that is compatible with `onnx 1.13.0` and with `tensorflow 2.9.2`? What version are you using? Could you include a requirements.txt file so I could replicate your environment?

**Comment by aslisabanci** [comment]
This is weird because there's no mention of onnx in the latest version of the notebook. So I'm suspecting that it's not trying to install the dependencies on a clean environment. Can you please try to run the notebook on Colab?

**Comment by mdhannadr** [comment]
Yes, it works in Colab! Very strange, apologies for the confusion. Everything looks good, thank you!

**Review by mdhannadr — APPROVED** [review]

**Comment by aslisabanci** [comment]
Thank you on the contrary from my side, for taking the time to review this. Cheers!

**Pull request merged**
